services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: cactus_tim
      POSTGRES_PASSWORD: 132369
      POSTGRES_DB: monika_bot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  monika_bot:
    build: .
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data: